services:
  # Config setup
  configs1:
    image: mongo:7.0.17
    container_name: configs1
    command: mongod --configsvr --replSet cfgrs
    volumes:
      - configs1:/data/db
    networks:
      - cluster_subnet

  configs2:
    image: mongo:7.0.17
    container_name: configs2
    command: mongod --configsvr --replSet cfgrs
    volumes:
      - configs2:/data/db
    networks:
      - cluster_subnet

  configs3:
    image: mongo:7.0.17
    container_name: configs3
    command: mongod --configsvr --replSet cfgrs
    volumes:
      - configs3:/data/db
    networks:
      - cluster_subnet

  config-setup:
    image: mongo:7.0.17
    container_name: config-setup
    command: mongosh --host configs1:27019 /usr/local/etc/mongo/config-init.js
    depends_on:
      - configs1
      - configs2
      - configs3
    volumes:
      - ./config-init.js:/usr/local/etc/mongo/config-init.js:ro
    networks:
      - cluster_subnet

volumes:
  configs1:
  configs2:
  configs3:
