include:
  - docker-compose.networks.yml
  - docker-compose.configs.yml
  - docker-compose.shards.yml

services:
  # Router setup
  router:
    image: mongo:7.0.17
    container_name: router
    command: mongos --configdb cfgrs/configs1:27019,configs2:27019,configs3:27019 --bind_ip 0.0.0.0 --port 27017
    depends_on:
      - config-setup
      - shard1-setup
      - shard2-setup
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 1s
      timeout: 5s
      retries: 3
      start_period: 2s
    ports:
      - '27017:27017'
    volumes:
      - router:/data/db
    networks:
      - cluster_subnet

  router-setup:
    image: mongo:7.0.17
    container_name: router-setup
    command: mongosh --host router:27017 /usr/local/etc/mongo/router-init.js
    depends_on:
      router:
        condition: service_healthy
    volumes:
      - ./router-init.js:/usr/local/etc/mongo/router-init.js:ro
    networks:
      - cluster_subnet

volumes:
  router:
