services:
  redis-node-1:
    image: valkey/valkey:8.0.0
    container_name: redis-node-1
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6381", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    ports:
      - '6381:6381'
    volumes:
      - redis-node-1-data:/var/lib/redis
      - ./redis-node-1.conf:/usr/local/etc/redis/redis.conf
    networks:
      cluster_subnet:
        ipv4_address: 10.63.79.11

  redis-node-2:
    image: valkey/valkey:8.0.0
    container_name: redis-node-2
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6382", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    ports:
      - '6382:6382'
    volumes:
      - redis-node-2-data:/var/lib/redis
      - ./redis-node-2.conf:/usr/local/etc/redis/redis.conf
    networks:
      cluster_subnet:
        ipv4_address: 10.63.79.12

  redis-node-3:
    image: valkey/valkey:8.0.0
    container_name: redis-node-3
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6383", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    ports:
      - '6383:6383'
    volumes:
      - redis-node-3-data:/var/lib/redis
      - ./redis-node-3.conf:/usr/local/etc/redis/redis.conf
    networks:
      cluster_subnet:
        ipv4_address: 10.63.79.13

  redis-node-4:
    image: valkey/valkey:8.0.0
    container_name: redis-node-4
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6384", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    ports:
      - '6384:6384'
    volumes:
      - redis-node-4-data:/var/lib/redis
      - ./redis-node-4.conf:/usr/local/etc/redis/redis.conf
    networks:
      cluster_subnet:
        ipv4_address: 10.63.79.14

  redis-node-5:
    image: valkey/valkey:8.0.0
    container_name: redis-node-5
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6385", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    ports:
      - '6385:6385'
    volumes:
      - redis-node-5-data:/var/lib/redis
      - ./redis-node-5.conf:/usr/local/etc/redis/redis.conf
    networks:
      cluster_subnet:
        ipv4_address: 10.63.79.15

  redis-node-6:
    image: valkey/valkey:8.0.0
    container_name: redis-node-6
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6386", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    ports:
      - '6386:6386'
    volumes:
      - redis-node-6-data:/var/lib/redis
      - ./redis-node-6.conf:/usr/local/etc/redis/redis.conf
    networks:
      cluster_subnet:
        ipv4_address: 10.63.79.16

  redis-cluster-setup:
    image: valkey/valkey:8.0.0
    command: valkey-cli --cluster create 10.63.79.11:6381 10.63.79.12:6382 10.63.79.13:6383 10.63.79.14:6384 10.63.79.15:6385 10.63.79.16:6386 --cluster-replicas 1 --cluster-yes
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
    networks:
      - cluster_subnet

volumes:
  redis-node-1-data:
  redis-node-2-data:
  redis-node-3-data:
  redis-node-4-data:
  redis-node-5-data:
  redis-node-6-data:

networks:
  cluster_subnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.63.79.0/24
